### ISSUE TITLE
WPE 20160804 does not select wayland backend

### ISSUE THREAD

**Issue by mihailescu2m** [WPEWebKit/WPEWebKit-upstream#33]
After a successful build, I was not able to start WPE under wayland.
My system is Odroid XU4 (Exynos5422), using ARM Mali Wayland drivers r10p0. I tried both in Weston and gnome-shell wayland session, but Wayland backend is not selected properly.
I added printf's (prefixed by `my_debug` message) to the functions in  `Source/WebCore/platform/graphics/wayland/PlatformDisplayWayland.cpp` and in `Source/WebCore/platform/graphics/wpe/PlatformDisplayWPE.cpp` - but only the printf in PlatformDisplayWPE is hit, the ones in PlatformDisplayWayland are not being called.

This is a log from weston-terminal:

```
odroid@odroid:/mnt/src/wpe$ WPE_BACKEND=wayland Tools/Scripts/run-wpe http://www.bouncyballs.org
Starting WPELauncher.
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
my_debug: m_backend = -1362096656
PlatformDisplayWPE: could not create the EGL display.
/mnt/src/webkit/WebKitBuild/Release/bin/WPEWebProcess: symbol lookup error: /usr/lib/arm-linux-gnueabihf/egl-current/libGLESv2.so.2: undefined symbol: wl_proxy_marshal_constructor_versioned

```

Any idea why this happens?

PS: This is the list of wl\* functions exported by `/usr/lib/arm-linux-gnueabihf/egl-current/libGLESv2.so.2`:

```
odroid@odroid:/mnt/src/wpe$ nm -D --defined-only /usr/lib/arm-linux-gnueabihf/egl-current/libGLESv2.so.2 | grep wl
001285f8 T wl_egl_window_create
001286c0 T wl_egl_window_destroy
00128714 T wl_egl_window_get_attached_size
00128690 T wl_egl_window_release
001286c8 T wl_egl_window_resize
00128664 T wl_egl_window_retain
```

`wl_proxy_marshal_constructor_versioned` is defined but not exported.

**Comment by zdobersek** [comment]
We don't use PlatformDisplayWayland (it's not even compiled), so that's why debug output from there is missing.

`wl_proxy_marshal_constructor_versioned` should be defined in `libwayland-client.so`. I suppose `libWPE-mesa.so` depends on it, but isn't linked against `libwayland-client.so`. Can you check that `ldd libWPE-mesa.so` lists `libwayland-client.so`?
